describe('57775 Autenticación de Usuarios mediante Login', () => {
    beforeEach(() => {
        allure.epic("Sprint 1");
        allure.feature("Autenticación de Usuarios mediante Login");
        cy.visit('https://celerisawsqa.tps.net.co/auth/login')
    })
    it('CP1_Campos obligatorios pantalla inicial', () => {
        cy.get('button[type="submit"]').contains('Ingresar').click()
        cy.contains('p.text-red-500', 'El usuario es requerido y debe tener al menos 7 caracteres.')
            .should('be.visible')
        cy.contains('p.text-red-500', 'La contraseña es requerida y debe tener al menos 8 caracteres.')
            .should('be.visible')
        cy.reload()
        cy.get('input[placeholder="Usuario"]').type('1073253202')
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.contains('p.text-red-500', 'La contraseña es requerida y debe tener al menos 8 caracteres.')
            .should('be.visible')
        cy.wait(4000)
        cy.reload()
        cy.get('input[placeholder="Contraseña"]').type('1073253202')
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.contains('p.text-red-500', 'El usuario es requerido y debe tener al menos 7 caracteres.')
            .should('be.visible')
    })
    it('CP3_Login exitoso redirección home', ()=> {
        cy.get('input[placeholder="Usuario"]').type(Cypress.env('user'))
        cy.get('input[placeholder="Contraseña"]').type(Cypress.env('pass'))
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard');
    })
    it('CP4_Login usuario inexistente o inactivo', ()=>{
        cy.get('input[placeholder="Usuario"]').type('andres.quimbayo@greg.com')
        cy.get('input[placeholder="Contraseña"]').type('Bogota.20250*')
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.contains('.text-sm.text-gray-500.mt-2.px-4.font-paragraph', 'Usuario y/o Contraseña incorrecta, por favor verifique la información')
            .should('be.visible')
    })
    it('CP5_Validaciones del campo Contraseña', ()=>{
        cy.get('input[placeholder="Usuario"]').type('andres.quimbayo@thomasgreg.com')
        cy.get('input[placeholder="Contraseña"]').type('maria.sanchezcsanchezcsanc22222')
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.contains('.text-sm.text-gray-500.mt-2.px-4.font-paragraph', 'Usuario y/o Contraseña incorrecta, por favor verifique la información')
            .should('be.visible')
        cy.contains('button', 'Cerrar').click({ force: true })
        cy.get('input[placeholder="Contraseña"]').invoke('val').then((val) => {expect(val.length).to.be.lte(30)})
        cy.reload()
        cy.get('input[placeholder="Contraseña"]').type('maria.sanchezc@thomasgreg.com')
        cy.get('.svg-inline--fa[data-icon="eye"]').click()
        cy.get('input[placeholder="Contraseña"]').should('have.value','maria.sanchezc@thomasgreg.com')
        cy.get('.svg-inline--fa[data-icon="eye-slash"]').click()
    })
    it('CP8_Seguridad en sesión', () => {
        cy.get('input[placeholder="Usuario"]').type(Cypress.env('user'))
        cy.get('input[placeholder="Contraseña"]').type(Cypress.env('pass'))
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard');
        cy.get('button[aria-label="Configuración"]').click()
        cy.contains('a', 'Cerrar Sesión').should('be.visible').click()
        cy.go('back')
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/auth/login');
    })
})
