describe('57827 Configurar fechas por etapas', ()=>{
    beforeEach(() => {
        allure.feature('Configurar fechas por etapas')
        allure.epic('Sprint 2')
        cy.visit(Cypress.env('urlBase'))
        cy.get('input[placeholder="Usuario"]').type(Cypress.env('user'))
        cy.get('input[placeholder="Contraseña"]').type(Cypress.env('pass'))
        cy.wait(3000)
        cy.contains('button', 'Ingresar').click();
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard')
    })
    it('CP01_Validar la estructura completa de la pantalla', () => {
        cy.contains('Configurar Fechas por etapa').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/configure-stage-dates');
        cy.wait(5000)
        cy.contains('span','Configuración de fechas por etapas').should('be.visible')
        cy.contains('span','Datos de la elección').should('be.visible')
        cy.contains('span','Creación de Delegados de Puesto').should('be.visible')
        cy.contains('button','Guardar').should('be.visible')
        cy.contains('button','Limpiar').should('be.visible')
        cy.get('.inline-flex.items-center.justify-between.w-full').should('be.visible')
        cy.get('.inline-flex.items-center.justify-between.w-full').should('be.visible').and('contain.text','Automatización etapa')
    })
    it('CP02_Validar el comportamiento del acordeón.', () => {
        cy.contains('Configurar Fechas por etapa').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/configure-stage-dates');
        cy.contains('span','Configuración de fechas por etapas').should('be.visible')
        cy.contains('span','Datos de la elección').should('be.visible').click({force: true})
        cy.contains('span','Creación de Delegados de Puesto').should('be.visible').click({force: true})
    })
    it('CP03_Validar el Comportamiento de listas desplegables y dependencias', () => {
        cy.contains('Configurar Fechas por etapa').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/configure-stage-dates');
        cy.contains('span','Configuración de fechas por etapas').should('be.visible')
        cy.wait(5000)
        cy.contains('span','Cac etapa automatizada').should('be.visible').and('contain.text','Cac etapa automatizada').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(0).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("AMAZONAS", {force: true})
        cy.contains('ul li','AMAZONAS').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(1).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("LETICIA", {force: true})
        cy.contains('ul li','LETICIA').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(2).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("ZONA 01", {force: true})
        cy.contains('ul li','ZONA 01').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("JORGE ELIECER GAITAN", {force: true})
        cy.contains('ul li','JORGE ELIECER GAITAN').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("MESA 1",{force: true})
        cy.contains('ul li','Mesa 1').click({force: true})
    })
    it('CP04_Validaciones de campos (agrupación de todas las validaciones)', () => {
        cy.contains('Configurar Fechas por etapa').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/configure-stage-dates');
        cy.contains('span','Configuración de fechas por etapas').should('be.visible')
        cy.contains('span','Datos de la elección').should('be.visible')
        cy.contains('span','Creación de Delegados de Puesto').should('be.visible')
        cy.contains('button','Guardar').should('be.visible')
        cy.contains('button','Limpiar').should('be.visible')
        cy.get('[placeholder="Nombre"]').first().click({force: true})
        cy.wait(1000)
        cy.get('input[type="text"]').clear();
        cy.contains('button','Guardar').should('be.visible').click({force: true})
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text',' Este campo es obligatorio. ')
        cy.wait(1000)
        cy.get('input[type="text"]').type('asdasdadadasdasdasdadadasdasdasdadadasdasdasdadadasdasdasdadadasdasdasdadadasdasdasdadadasdasdasdadaa');
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text',' Ha excedido el límite de caracteres permitido ')
        cy.wait(1000)
        cy.get('input[data-errorkey="electionDate"]').first().clear().type('2026-11-20T18:56');
        cy.wait(1000)
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').first().should('be.visible').and('contain.text',' El valor ingresado en el campo Fecha y hora inicio es superior al valor ingresado en el campo Fecha y hora fin ')
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').last().should('be.visible').and('contain.text',' El valor ingresado en el campo Fecha y hora fin es inferior al valor ingresado en el campo Fecha y hora inicio ')
        cy.get('input[data-errorkey="electionDate"]').first().type('2025-11-03T18:56');
    })
    it('CP05_Validar que no permita guardar si existen errores o campos vacíos', () => {
        cy.contains('Configurar Fechas por etapa').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/configure-stage-dates');
        cy.contains('span','Configuración de fechas por etapas').should('be.visible')
        cy.contains('span','Datos de la elección').should('be.visible')
        cy.contains('span','Creación de Delegados de Puesto').should('be.visible')
        cy.contains('button','Guardar').should('be.visible')
        cy.contains('button','Limpiar').should('be.visible')
        cy.get('[placeholder="Nombre"]').first().click({force: true})
        cy.get('input.placeholder\\:text-gray-300').clear();
        cy.get('input.placeholder\\:text-gray-300').clear();
        cy.wait(9000)
        cy.contains('button','Guardar').should('be.visible').click({force: true})
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text',' Este campo es obligatorio. ')
    })
    it('CP06_Validad Funcionalidad de Guardar flujo completo', () => {
        cy.contains('Configurar Fechas por etapa').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/configure-stage-dates');
        cy.contains('span','Configuración de fechas por etapas').should('be.visible')
        cy.wait(2000)
        cy.get('input[type="text"]').clear()
        cy.get('input[type="text"]').type('Automatizadas')
        cy.get('input[data-errorkey="electionDate"]').first().clear().type('2025-10-01T18:56');
        cy.wait(5000)
        cy.contains('span','Cac etapa automatizada').should('be.visible').and('contain.text','Cac etapa automatizada').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(0).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("AMAZONAS", {force: true})
        cy.contains('ul li','AMAZONAS').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(1).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("LETICIA", {force: true})
        cy.contains('ul li','LETICIA').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(2).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("ZONA 01", {force: true})
        cy.contains('ul li','ZONA 01').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("JORGE ELIECER GAITAN", {force: true})
        cy.contains('ul li','JORGE ELIECER GAITAN').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("MESA 1",{force: true})
        cy.contains('ul li','Mesa 1').click({force: true})
        cy.get('input[data-errorkey="1721.stage.start"]').scrollIntoView();
        cy.get('input[data-errorkey="1721.stage.start"]').first().clear().type('2025-12-01T18:56');
        cy.get('input[data-errorkey="1721.stage.end"]').first().clear().type('2025-12-31T18:56');
        cy.contains('button','Guardar').scrollIntoView();
        cy.contains('button','Guardar').should('be.visible').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de guardar la configuración realizada?')
        cy.contains('button','No').should('be.visible').click({force: true})
        cy.contains('button','Guardar').should('be.visible').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de guardar la configuración realizada?')
        cy.contains('button','Sí').should('be.visible').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','Se ha realizado la configuración de las fechas por etapas correctamente')
    })
    it('CP07_Validar la Funcionalidad Limpiar', () => {
        cy.contains('Configurar Fechas por etapa').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/configure-stage-dates');
        cy.contains('span','Configuración de fechas por etapas').should('be.visible')
        cy.wait(2000)
        cy.get('input[type="text"]').clear()
        cy.get('input[type="text"]').type('Automatizadas')
        cy.get('input[data-errorkey="electionDate"]').first().clear().type('2025-10-01T18:56');
        cy.wait(5000)
        cy.contains('span','Cac etapa automatizada').should('be.visible').and('contain.text','Cac etapa automatizada').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(0).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("AMAZONAS", {force: true})
        cy.contains('ul li','AMAZONAS').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(1).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("LETICIA", {force: true})
        cy.contains('ul li','LETICIA').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(2).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("ZONA 01", {force: true})
        cy.contains('ul li','ZONA 01').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("JORGE ELIECER GAITAN", {force: true})
        cy.contains('ul li','JORGE ELIECER GAITAN').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force: true})
        cy.get('[placeholder="Buscar..."]').click({force: true})
        cy.get('[placeholder="Buscar..."]').type("MESA 1",{force: true})
        cy.contains('ul li','Mesa 1').click({force: true})
        cy.get('input[data-errorkey="1721.stage.start"]').scrollIntoView();
        cy.get('input[data-errorkey="1721.stage.start"]').first().clear().type('2025-10-01T18:56');
        cy.get('input[data-errorkey="1721.stage.end"]').first().clear().type('2025-10-01T18:56');
        cy.contains('button','Limpiar').should('be.visible').click({force: true})
    })
})