describe('58379 Modificación de sub - actividad para una actividad', () => {
    beforeEach(() => {
        allure.epic("Sprint 2")
        allure.feature("Modificación de sub - actividad para una actividad")
        cy.visit(Cypress.env('urlBase'))
        cy.get('input[placeholder="Usuario"]').type(Cypress.env('user'))
        cy.get('input[placeholder="Contraseña"]').type(Cypress.env('pass'))
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.screenshot('Paso 1 Login exitoso', {capture: 'runner'});
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard')
        cy.contains('Administrar Actividades').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/manage-activities');
    })
    it('CP1_Validar acceso desde el listado de sub-actividades',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
    })
    it('CP2_Validar estructura de la modal de editar sub-actividades',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible')
        cy.get('.flex.transition-all.text-center.duration-300.ease-in-out.text-wrap.break-words.outline-1').should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible')
        cy.get('.bg-transparent.border.border-blue-900.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full').eq(2).should('be.visible')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full').last().should('be.visible')
    })
    it('CP3_Validar listas desplegables etapa y nombre de actividad',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar etapa')
        cy.contains('li','Automatizar etapa').click()
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar actividad')
        cy.contains('li','Automatizar actividad').click()
    })
    it('CP4_Validar el comportamiento del campo tipo de delegado',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.flex.transition-all.text-center.duration-300.ease-in-out.text-wrap.break-words.outline-1').should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar etapa')
        cy.contains('li','Automatizar etapa').click()
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar actividad')
        cy.contains('li','Automatizar actividad').click()
        cy.get('.flex.transition-all.text-center.duration-300.ease-in-out.text-wrap.break-words.outline-1').should('be.visible').and('contain.text',' Delegado de puesto logístico ')
    })
    it('CP5_Validacion del campo Nombre Subactividad vació',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar etapa')
        cy.contains('li','Automatizar etapa').click()
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar actividad')
        cy.contains('li','Automatizar actividad').click()
        cy.get('.flex.transition-all.text-center.duration-300.ease-in-out.text-wrap.break-words.outline-1').should('be.visible').and('contain.text',' Delegado de puesto logístico ')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible').clear()
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full').last().should('be.visible').click()
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','Por favor, complete todos los campos requeridos.')
    })
    it('CP6_Validar longitud del campo Nombre de sub-actividad',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar etapa')
        cy.contains('li','Automatizar etapa').click()
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar actividad')
        cy.contains('li','Automatizar actividad').click()
        cy.get('.flex.transition-all.text-center.duration-300.ease-in-out.text-wrap.break-words.outline-1').should('be.visible').and('contain.text',' Delegado de puesto logístico ')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().type('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').last().should('be.visible').and('contain.text',' Ha excedido el límite de caracteres permitido. ')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full').last().should('be.visible').click()
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','Por favor, complete todos los campos requeridos.')
    })
    it('CP7_Validación de duplicado del nombre sub-actividad para la misma actividad y etapa',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar etapa')
        cy.contains('li','Automatizar etapa').click()
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar actividad')
        cy.contains('li','Automatizar actividad').click()
        cy.get('.flex.transition-all.text-center.duration-300.ease-in-out.text-wrap.break-words.outline-1').should('be.visible').and('contain.text',' Delegado de puesto logístico ')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible').clear()
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().type('Pruebaqa108')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full').last().should('be.visible').click()
        cy.get('.bg-blue-btn').last().click();
        cy.get('p.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('have.text', 'Ya existe una sub-actividad con este nombre en esta actividad.');
    })
    it('CP8_Validar que el campo Actividad sea obligatorio',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar etapa')
        cy.contains('li','Automatizar etapa').click()
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().type('Pruebaqa108')
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').last().should('be.visible').and('contain.text','Este campo es obligatorio.')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full').last().should('be.visible').click()
        cy.get('.bg-blue-btn').last().click();
    })
    it('CP9_Validar que el campo Etapa sea obligatorio',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().type('Pruebaqa108')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full').last().should('be.visible').click()
        cy.get('.bg-blue-btn').last().click();
    })
    it('CP10_Validar que el campo Estado sea obligatorio',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full').last().should('be.visible').click()
        cy.get('.bg-blue-btn').last().click();
    })
    it('CP11_Validar pop up o mensaje de confirmación de cambios',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar etapa')
        cy.contains('li','Automatizar etapa').click()
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar actividad')
        cy.contains('li','Automatizar actividad').click()
        cy.get('.flex.transition-all.text-center.duration-300.ease-in-out.text-wrap.break-words.outline-1').should('be.visible').and('contain.text',' Delegado de puesto logístico ')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible').clear()
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().type('Pruebaqa108')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full').last().should('be.visible').click()
        cy.get('p.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de realizar la edición de la subactividad?')
        cy.get('button.bg-transparent.border-blue-900').last().should('be.visible').click({force: true});
    })
    it('CP12_Validar comportamiento botón Cancelar y botón Cerrar del form',()=>{
        cy.contains('button','Consultar').click({force: true})
        cy.get('celeris-search-outline-icon').last().should('be.visible').click({force: true})
        cy.contains('span','Nombre de la subactividad').should('be.visible')
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
        cy.get('.text-lg.font-title.font-medium.capitalize').should('be.visible').and('contain.text','Editar Sub-Actividad para una etapa')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar etapa')
        cy.contains('li','Automatizar etapa').click()
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click()
        cy.get('[placeholder="Buscar..."]').type('Automatizar actividad')
        cy.contains('li','Automatizar actividad').click()
        cy.get('.flex.transition-all.text-center.duration-300.ease-in-out.text-wrap.break-words.outline-1').should('be.visible').and('contain.text',' Delegado de puesto logístico ')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible').clear()
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().type('Pruebaqa108')
        cy.get('.bg-transparent.border.border-blue-900.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full').eq(2).should('be.visible').click()
    })
})