describe('58291 Creación de etapa del proceso electoral', () => {
    beforeEach(() => {
        cy.visit('https://celerisawsqa.tps.net.co/auth/login')
        cy.viewport(1920, 1080)
    })
    it('CP01 Visualización del formulario de creación de etapa', () => {
        cy.get('input[placeholder="Usuario"]').type('andres.quimbayo@thomasgreg.com')
        cy.get('input[placeholder="Contraseña"]').type('Bogota.2025*')
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.get('.px-6.py-2').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard');
        cy.contains('Administrar Etapa Proceso Electoral').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/manage-stages');
        cy.get('.button.bg-linear-90').click()
        cy.get('.text-lg.font-title.font-medium').should('have.text', 'Crear Etapa Del Proceso')
        cy.get('.button.duration-300').contains('Guardar').should('be.visible');
    })
    it('CP02 Creación exitosa de una nueva etapa', () => {
        cy.get('input[placeholder="Usuario"]').type('andres.quimbayo@thomasgreg.com')
        cy.get('input[placeholder="Contraseña"]').type('Bogota.2025*')
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.get('.px-6.py-2').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard');
        cy.contains('Administrar Etapa Proceso Electoral').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/manage-stages');
        cy.get('.button.bg-linear-90').click()
        const random = 'PruebaQA' + Math.floor(Math.random() * 1000)
        cy.get('input[placeholder="Bitácora"]').type(random)
        cy.log('Nombre de etapa: ' + random)
        cy.contains('div', 'Delegado Funcional').click()
        cy.contains('div', 'Delegado Logistico').click()
        cy.contains('div', 'Delegado Logistico Funcional').click()
        cy.get('.button.duration-300').contains('Guardar').click()
        cy.get('.text-sm.text-gray-500.mt-2.px-4').contains('El registro ha sido creado con exito').should('be.visible');
    })
    it('CP03 Validación de campos obligatorios y mensajes de validación', () => {
        cy.get('input[placeholder="Usuario"]').type('andres.quimbayo@thomasgreg.com')
        cy.get('input[placeholder="Contraseña"]').type('Bogota.2025*')
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.get('.px-6.py-2').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard');
        cy.contains('Administrar Etapa Proceso Electoral').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/manage-stages');
        cy.get('.button.bg-linear-90').click()
        cy.get('.button.duration-300').contains('Guardar').click()
        cy.get('.px-6.py-2').click()
        cy.get('.text-red-500.text-xs.italic.mt-1').contains(' El nombre de la etapa es requerido. ').should('have.text', ' El nombre de la etapa es requerido. ')
        cy.get('.text-red-500.text-xs.italic.mt-1').contains(' El tipo de delegado es requerido. ').should('have.text', ' El tipo de delegado es requerido. ')
        const random = 'Lorema Ipsum es simpleme el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias' + Math.floor(Math.random() * 100)
        cy.log(random)
        cy.get('input[placeholder="Bitácora"]').type(random)
        cy.contains('div', 'Delegado Funcional').click()
        cy.get('.button.duration-300').contains('Guardar').click()
        cy.get('input[placeholder="Bitácora"]').invoke('val').then((valor) => {
            expect(valor.length).to.be.lte(150)
        })
        cy.get('.text-sm.text-gray-500.mt-2.px-4').contains('El registro ha sido creado con exito').click()
        cy.get('.button.bg-linear-90').click()
        cy.get('input[placeholder="Bitácora"]').type('PruebaQA')
        cy.contains('div', 'Delegado Funcional').click()
        cy.contains('div', 'Delegado Logistico').click()
        cy.contains('div', 'Delegado Logistico Funcional').click()
        cy.get('.button.duration-300').contains('Guardar').click()
    })
    it('CP04 Cancelación de la creación de etapa', ()=>{
        cy.get('input[placeholder="Usuario"]').type('andres.quimbayo@thomasgreg.com')
        cy.get('input[placeholder="Contraseña"]').type('Bogota.2025*')
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.get('.px-6.py-2').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard');
        cy.contains('Administrar Etapa Proceso Electoral').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/manage-stages');
        cy.get('.button.bg-linear-90').click()
        cy.get('input[placeholder="Bitácora"]').type('PRUEBAS')
        cy.contains('div', 'Delegado Logistico Funcional').click()
        cy.get('.button.bg-transparent').contains('Cancelar').click()
        cy.get('.button.bg-linear-90').click()
        cy.get('input[placeholder="Bitácora"]').type('PRUEBAS')
        cy.contains('div', 'Delegado Logistico Funcional').click()
        cy.get('.transition-all.duration-300.flex.flex-row').contains('Cerrar').click()
    })
    it('CP05 Visualización de etapas duplicadas. (Confirmar y Cancelar Duplicados)', ()=>{
        cy.get('input[placeholder="Usuario"]').type('andres.quimbayo@thomasgreg.com')
        cy.get('input[placeholder="Contraseña"]').type('Bogota.2025*')
        cy.wait(4000)
        cy.get('button[type="submit"]').contains('Ingresar').dblclick({force: true})
        cy.get('.px-6.py-2').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard');
        cy.contains('Administrar Etapa Proceso Electoral').click()
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/manage-stages');
        cy.get('.button.bg-linear-90').click()
        cy.get('input[placeholder="Bitácora"]').type('PruebaQA')
        cy.contains('div', 'Delegado Funcional').click()
        cy.contains('div', 'Delegado Logistico').click()
        cy.contains('div', 'Delegado Logistico Funcional').click()
        cy.get('.button.duration-300').contains('Guardar').click()
        cy.get('.text-sm.text-gray-500.mt-2.px-4').should('have.text','El registro ya existe')
        cy.get('.px-6.py-2').click()
        cy.get('.button.bg-transparent').contains('Cancelar').click()
        cy.get('.button.bg-linear-90').click()
        cy.get('input[placeholder="Bitácora"]').type('pruebaqa')
        cy.contains('div', 'Delegado Logistico Funcional').click()
        cy.get('.button.duration-300').contains('Guardar').click()
        cy.get('.text-sm.text-gray-500.mt-2.px-4').should('have.text','El registro ya existe')
        cy.get('.px-6.py-2').click()
        cy.get('.button.bg-transparent').contains('Cancelar').click()
        cy.get('.button.bg-linear-90').click()
        cy.get('input[placeholder="Bitácora"]').type('PRUEBAQA')
        cy.contains('div', 'Delegado Logistico Funcional').click()
        cy.get('.button.duration-300').contains('Guardar').click()
        cy.get('.text-sm.text-gray-500.mt-2.px-4').should('have.text','El registro ya existe')
    })
})