describe('58367 Eliminar pregunta por actividad o subactividad', ()=>{
    beforeEach( ()=>{
        allure.epic('Sprint 3')
        allure.feature('Eliminar pregunta por actividad o subactividad')
        cy.visit(Cypress.env('urlBase'))
        cy.get('input[placeholder="Usuario"]').type(Cypress.env('user'))
        cy.get('input[placeholder="Contraseña"]').type(Cypress.env('pass'))
        cy.wait(3000)
        cy.contains('button', 'Ingresar').click();
        cy.url().should('eq','https://celerisawsqa.tps.net.co/dashboard')
        cy.contains('Administrar Pregunta por Actividad').click({force: true})
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/manage-questions');
        cy.get('.font-medium.text-h2.text-lg').should('be.visible').and('contain.text','Administración de preguntas por actividad')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(0).click({force: true})
        cy.get('input[placeholder="Buscar..."]').click({force: true})
        cy.get('input[placeholder="Buscar..."]').type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(1).click({force: true})
        cy.get('input[placeholder="Buscar..."]').click({force: true})
        cy.get('input[placeholder="Buscar..."]').type('Automatizar actividad')
        cy.contains('ul li','Automatizar actividad').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(2).click({force: true})
        cy.get('input[placeholder="Buscar..."]').click({force: true})
        cy.get('input[placeholder="Buscar..."]').type('Automatizacion sub actividad no tocar')
        cy.contains('ul li','Automatizacion sub actividad no tocar').click({force: true})
        cy.contains('button','Consultar').click({force: true})
        cy.wait(1000)
    })
    it('CP01_Validar que al ingresar al modulo se visualice el botón de Eliminar en la columna de acciones', ()=>{
        cy.get('celeris-trash-outline-icon').last().should('be.visible')
    })
    it('CP02_Validar que al hacer clic en el icono de eliminar se muestre la modal de confirmación', ()=>{
        cy.get('celeris-trash-outline-icon').last().should('be.visible').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de que desea eliminar la pregunta seleccionada? Esta acción no se puede deshacer.')
    })
    it('CP03_En el modal de confirmación hacer clic en la opción NO', ()=>{
        cy.get('celeris-trash-outline-icon').last().should('be.visible').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de que desea eliminar la pregunta seleccionada? Esta acción no se puede deshacer.')
        cy.contains('button','No').should('be.visible').click({force: true})
    })
    it('CP04_Eliminar pregunta exitosamente', ()=>{
        cy.get('celeris-trash-outline-icon').last().should('be.visible').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de que desea eliminar la pregunta seleccionada? Esta acción no se puede deshacer.')
        cy.contains('button','Sí').should('be.visible').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','La pregunta ha sido eliminada exitosamente.')
    })
})