describe('58366 Modificación de pregunta por actividad o subactividad', ()=>{
    beforeEach( ()=>{
        allure.epic('Sprint 3')
        allure.feature('Modificación de pregunta por actividad o subactividad')
        cy.visit(Cypress.env('urlBase'))
        cy.get('input[placeholder="Usuario"]').type(Cypress.env('user'))
        cy.get('input[placeholder="Contraseña"]').type(Cypress.env('pass'))
        cy.wait(3000)
        cy.get('button[type=submit]').click({force: true})
        cy.url().should('eq','https://celerisawsqa.tps.net.co/dashboard')
        cy.contains('Administrar Pregunta por Actividad').click({force: true})
        cy.url().should('eq', 'https://celerisawsqa.tps.net.co/dashboard/parameterization/manage-questions');
        cy.get('.font-medium.text-h2.text-lg').should('be.visible').and('contain.text','Administración de preguntas por actividad')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(0).click({force: true})
        cy.get('input[placeholder="Buscar..."]').click({force: true})
        cy.get('input[placeholder="Buscar..."]').type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(1).click({force: true})
        cy.get('input[placeholder="Buscar..."]').click({force: true})
        cy.get('input[placeholder="Buscar..."]').type('Automatizar actividad')
        cy.contains('ul li','Automatizar actividad').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(2).click({force: true})
        cy.get('input[placeholder="Buscar..."]').click({force: true})
        cy.get('input[placeholder="Buscar..."]').type('Automatizacion sub actividad no tocar')
        cy.contains('ul li','Automatizacion sub actividad no tocar').click({force: true})
        cy.contains('button','Consultar').click({force: true})
        cy.wait(1000)
        cy.get('celeris-pencil-draw-outline-icon').last().click({force: true})
    })
    it('CP01_Acceso a la pantalla de edición', ()=>{
        cy.get('.text-xl.font-semibold.text-gray-900').should('be.visible').and('contain.text','Editar Pregunta')
    })
    it('CP02_Estructura de la pantalla / modal de edición', ()=>{
        cy.get('.text-xl.font-semibold.text-gray-900').should('be.visible').and('contain.text','Editar Pregunta')
        cy.get('select.w-full.px-3.py-2.bg-gray-50.border.border-gray-200').eq(0).find('option[value="839"]').should('exist').and('have.text', 'Automatizar etapa');
        cy.get('.w-full.px-3.py-2.bg-gray-50.border.border-gray-200').eq(1).should('contain.text','Automatizar actividad')
        cy.get('.w-full.px-3.py-2.bg-gray-50.border.border-gray-200').eq(2).should('contain.text','Automatizacion sub actividad no tocar')
        cy.get('input[placeholder="Text"]').first().should('have.attr', 'inputmode', 'numeric');
        cy.get('.w-full.px-3.py-2.bg-gray-50.border.border-gray-200').eq(4).should('have.prop','value').and('not.be.empty')
        cy.get('.w-5.h-5.text-blue-600.border-gray-300').first().should('be.visible').and('have.prop','checked',true)
        cy.get('.w-5.h-5.text-blue-600.border-gray-300').last().should('be.visible').and('have.prop','checked',false)
        cy.get('.w-11.h-6.bg-gray-200').should('be.visible')
    })
    it('CP03_Validaciones de campos del formulario', ()=>{
        cy.get('.text-xl.font-semibold.text-gray-900').should('be.visible').and('contain.text','Editar Pregunta')
        cy.get('input.w-full.px-3.py-2.bg-gray-50.border.border-gray-200.rounded-full.text-gray-500').eq(1).should('have.attr', 'maxlength', '250')
        cy.get('input.w-full.px-3.py-2.bg-gray-50.border.border-gray-200.rounded-full.text-gray-500').eq(1).clear()
        cy.get('input.w-full.px-3.py-2.bg-gray-50.border.border-gray-200.rounded-full.text-gray-500').eq(1).type('Pregunta automatizada no tocar')
        cy.contains('button','Guardar').click({force: true})
        cy.contains('button','Sí').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','Ya existe una pregunta configurada con las mismas características para esta actividad y/o sub-actividad')
        cy.contains('button','Aceptar').click({force: true})
        cy.get('.w-5.h-5.text-blue-600.border-gray-300').last().should('be.visible').click({force: true})
        cy.contains('button','Agregar Respuesta').click({force: true})
        cy.get('input[placeholder="Texto"]').eq(0).should('be.visible').type('HOLA')
        cy.get('input[placeholder="Texto"]').eq(1).should('be.visible').type('HOLA')
        cy.contains('button','Guardar').click({force: true})
        cy.get('.text-red-500.text-sm.mb-2').should('be.visible').and('contain.text','Ya existe una opción configurada con las mismas características para esta pregunta')
        cy.get('input[placeholder="Text"]').first().should('be.visible').type('Hola')
        cy.get('input.w-full.px-3.py-2.bg-gray-50.border.border-gray-200.rounded-full.text-gray-500').eq(1).clear()
        cy.get('select').eq(0).select('Seleccione una opción')
        cy.get('input[placeholder="Text"]').first().should('be.visible').clear()
        cy.contains('button','Guardar').click({force: true})
        cy.get('.text-red-500.text-sm.mt-1').should('have.length',4).and('contain.text','Este campo es obligatorio.')
    })
    it('CP04_Comportamiento de listas desplegables dependientes', ()=>{
        cy.get('.text-xl.font-semibold.text-gray-900').should('be.visible').and('contain.text','Editar Pregunta')
        cy.get('select').eq(0).select('Seleccione una opción')
        cy.get('select').eq(0).select('Automatizar etapa')
        cy.get('select').eq(1).select('Automatizar actividad')
        cy.get('select').last().select('Automatizacion sub actividad no tocar')
    })
    it('CP05_Tipo de respuesta', ()=>{
        cy.get('.text-xl.font-semibold.text-gray-900').should('be.visible').and('contain.text','Editar Pregunta')
        cy.get('.w-5.h-5.text-blue-600.border-gray-300').last().should('be.visible').click({force: true})
        cy.get('input[value=unica]').should('be.visible')
        cy.get('input[value=multiple]').should('be.visible')
        cy.get('input[value=multiple]').click({force: true})
        cy.contains('button','Agregar Respuesta').click({force: true})
        cy.get('[type="checkbox"]').last().should('be.visible')
        cy.get('.px-4.py-2.bg-white.border.border-blue-600').last().should('be.visible')
        cy.get('[type="checkbox"]').last().should('be.visible').click({force: true})
        cy.contains('span','Observación')
        cy.contains('span','Opción múltiple')
        cy.contains('span','Otra pregunta')
        cy.contains('span','Adjuntar archivo')
        cy.get('.px-4.py-2.bg-white.border.border-blue-600').last().click({force: true})
    })
    it('CP06_Botones del formulario', ()=>{
        cy.get('input.w-full.px-3.py-2.bg-gray-50.border.border-gray-200.rounded-full.text-gray-500').eq(1).clear()
        cy.fixture('crearEtapaPr').then((fixture) => {
            const random = Math.floor(Math.random() * 20000)
            const pregunta = `${fixture.pregunta}${random}`
            cy.get('input.w-full.px-3.py-2.bg-gray-50.border.border-gray-200.rounded-full.text-gray-500').eq(1).type(pregunta)
        })
        cy.fixture('crearEtapaPr').then((fixture) => {
            const random = Math.floor(Math.random() * 20)
            const ordenPregunta = `${fixture.orden}${random}`
            cy.get('[inputmode="numeric"]').clear()
            cy.get('[inputmode="numeric"]').type(ordenPregunta)
            cy.contains('button','Guardar').click({force: true})
            cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de realizar la actualización de la pregunta?')
            cy.contains('button','No').click({force: true})
            cy.contains('button','Guardar').click({force: true})
            cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de realizar la actualización de la pregunta?')
            cy.contains('button','Sí').click({force: true})
            cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','Pregunta actualizada exitosamente')
        })
    })
})