describe('57862 Crear delegado', ()=>{
    beforeEach( ()=>{
        allure.epic('Sprint 4')
        allure.feature('Crear delegado')
        cy.visit(Cypress.env('urlBase'))
        cy.get('input[placeholder="Usuario"]').type('45467')
        cy.get('input[placeholder="Contraseña"]').type('Bogota.2025*')
        cy.wait(4000)
        cy.contains('button','Ingresar').dblclick({force:true})
        cy.contains('a','Administrar Delegados de Puesto').click({force:true})
        cy.url().should('eq','https://celerisawsqa.tps.net.co/dashboard/delegates/manage-delegates')
    })
    it('CP01_Apertura del modal Crear delegado', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
    })
    it('CP02_Validar encabezado de módulo y submódulo y validar acciones rápidas disponibles', ()=>{
        cy.contains('span','Delegados de puesto')
        cy.contains('h2','Administración de delegados de puesto')
    })
    it('CP03_Verificación de tarjetas de métricas', ()=>{
        cy.get('.bg-white.flex.items-center.justify-between.min-h-24').should('be.visible').and('have.length','3')
    })
    it('CP04_Verificar menú lateral y opción Dashboard resaltada', ()=>{
        cy.get('a[href="/dashboard/delegates/manage-delegates"]').should('have.class', 'bg-[#07055C]');
    })
    it('CP05_Validación de búsqueda general', ()=>{
        cy.get('lucide-angular').first().click({force:true})
        cy.get('input[placeholder="Número de documento"]').first().click().type('506618')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300').first().click()
        cy.contains('span',' Cataño Sepulveda ')
    })
    it('CP06_Validar estructura de tabla de usuarios y validar paginador activo', ()=>{
        cy.get('lucide-angular').first().click({force:true})
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300').first().click()
        cy.get('table tbody tr').should('have.length', 15)
    })
    it('CP07_Validar estructura del formulario Crear Usuario', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('input[placeholder="Número de documento"]').eq(1).should('be.visible')
        cy.get('input[placeholder="Nombres de usuario"]').should('be.visible')
        cy.get('input[placeholder="Apellidos de usuario"]').should('be.visible')
        cy.get('input[placeholder="Texto"]').first().should('be.visible')
        cy.get('input[placeholder="Texto"]').eq(1).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(7).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(8).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(9).should('be.visible')
        cy.get('.flex.flex-wrap.gap-2.p-3.overflow-x-hidden').first().should('be.visible')
        cy.get('input[placeholder="Texto"]').eq(2).should('be.visible')
        cy.get('.bg-gray-100.bg-white.block.border.border-gray-300').should('be.visible')
        cy.contains('.button','Cancelar').scrollIntoView();
        cy.contains('button','Cancelar').should('be.visible')
        cy.contains('button','Guardar').should('be.visible')
    })
    it('CP08_Validar estado del campo Estado por defecto', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('.bg-gray-100.bg-white.block.border.border-gray-300').should('be.visible').and('have.prop','outerText','Activo')
    })
    it('CP09_Validar lupa al lado del campo Documento', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('input[placeholder="Número de documento"]').eq(1).click({force:true})
        cy.get('input[placeholder="Número de documento"]').eq(1).type("8731")
        cy.get('svg[data-icon="magnifying-glass"]').first().click({force:true})
        cy.get('input[placeholder="Nombres de usuario"]').should('have.prop','value','Elicio ')
    })
    it('CP10_Validación campo Número de documento obligatorio', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.contains('.button','Cancelar').scrollIntoView();
        cy.contains('button','Guardar').should('be.visible').click({force:true})
        cy.contains('.button','Cerrar').click({force:true})
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').first().should('be.visible').and('contain.text',' Este campo es obligatorio. ')
    })
    it('CP11_Validación formato del documento', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('input[placeholder="Número de documento"]').eq(1).click({force:true})
        cy.get('input[placeholder="Número de documento"]').eq(1).type("87318731873187318731")
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').first().should('be.visible').and('contain.text',' Ha excedido el límite de caracteres permitido ')
        cy.get('input[placeholder="Número de documento"]').eq(1).clear()
        cy.get('input[placeholder="Número de documento"]').eq(1).type("873187318731")
        cy.get('svg[data-icon="magnifying-glass"]').first().click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','El número de documento ingresado no tiene coincidencias en el ANI. Verifique la información.')
    })
    it('CP12_Validación de unicidad del número de documento', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('input[placeholder="Número de documento"]').eq(1).should('be.visible').type('5234')
        cy.get('svg[data-icon="magnifying-glass"]').first().click({force:true})
        cy.get('input[placeholder="Nombres de usuario"]').should('be.visible')
        cy.get('input[placeholder="Apellidos de usuario"]').should('be.visible')
        cy.get('input[placeholder="Texto"]').first().should('be.visible').type('3102137409')
        cy.get('input[placeholder="Texto"]').eq(1).should('be.visible').type('andre1@hotmail.com')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').type('Delegado puesto funcional')
        cy.contains('ul li','Delegado puesto funcional').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(8).should('be.visible').click()
        cy.get('input[placeholder="Buscar..."]').type('Localidad 11 suba')
        cy.contains('ul li','Localidad 11 suba').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(9).should('be.visible').click()
        cy.get('input[placeholder="Buscar..."]').type('Alberto lleras')
        cy.contains('ul li','Alberto lleras').click({force:true})
        cy.get('.text-xs.font-normal.w-4.h-4').first().should('be.visible').click({force:true})
        cy.contains('.button','Cancelar').scrollIntoView();
        cy.contains('button','Cancelar').should('be.visible')
        cy.contains('button','Guardar').should('be.visible').click({force:true})
        cy.contains('button','Sí').should('be.visible').click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','El número de documento 5234 ya existe en el sistema y se encuentra asignado como delegado de puesto: BOGOTA D.C., BOGOTA. D.C., LOCALIDAD 10 ENGATIVA, ALCALA SEDE B, 1.')
    })
    it('CP13_Consulta exitosa a ANI', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('input[placeholder="Número de documento"]').eq(1).click({force:true})
        cy.get('input[placeholder="Número de documento"]').eq(1).type("8731")
        cy.get('svg[data-icon="magnifying-glass"]').first().click({force:true})
        cy.get('input[placeholder="Nombres de usuario"]').should('have.prop','value','Elicio ')
    })
    it('CP14_Consulta fallida a ANI', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('input[placeholder="Número de documento"]').eq(1).click({force:true})
        cy.get('input[placeholder="Número de documento"]').eq(1).type("873187318731")
        cy.get('svg[data-icon="magnifying-glass"]').first().click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','El número de documento ingresado no tiene coincidencias en el ANI. Verifique la información.')
    })
    it('CP15_Validación de campos obligatorios', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.contains('.button','Cancelar').scrollIntoView();
        cy.contains('button','Guardar').should('be.visible').click({force:true})
        cy.contains('.button','Cerrar').click({force:true})
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text',' Este campo es obligatorio. ').and('have.length','11')
    })
    it('CP16_Validar lista de perfiles configurados y búsqueda dentro del dropdown Perfil', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').type('Delegado puesto funcional')
        cy.contains('ul li','Delegado puesto funcional').click({force:true})
    })
    it('CP17_Validación habilitación de Departamento y Municipio', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.wait(2000)
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible').and('have.prop','outerText','Bogota d.c.')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(7).should('be.visible').and('have.prop','outerText','Bogota. d.c.')
    })
    it('CP19_Validación campo Celular', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('input[placeholder="Texto"]').first().should('be.visible').type('4102137409')
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text','El número de celular debe tener un formato válido.  Este campo es obligatorio.')
    })
    it('CP20_Validación campo de correo', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('input[placeholder="Texto"]').eq(1).should('be.visible').type('andre1hotmail.com')
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text','Correo no válido')
    })
    it('CP21_Validación de botones Cancelar,Guardar y Cerrar', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.contains('.button','Cancelar').scrollIntoView();
        cy.contains('button','Cancelar').should('be.visible').click({force:true})
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.contains('button','Cerrar').should('be.visible').click({force:true})
    })
    it('CP22_Validar modal de confirmación de creación al guardar con todos los campos válidos', ()=>{
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('input[placeholder="Número de documento"]').eq(1).should('be.visible').type('5234')
        cy.get('svg[data-icon="magnifying-glass"]').first().click({force:true})
        cy.get('input[placeholder="Nombres de usuario"]').should('be.visible')
        cy.get('input[placeholder="Apellidos de usuario"]').should('be.visible')
        cy.get('input[placeholder="Texto"]').first().should('be.visible').type('3102137409')
        cy.get('input[placeholder="Texto"]').eq(1).should('be.visible').type('andre1@hotmail.com')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').type('Delegado puesto funcional')
        cy.contains('ul li','Delegado puesto funcional').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(8).should('be.visible').click()
        cy.get('input[placeholder="Buscar..."]').type('Localidad 11 suba')
        cy.contains('ul li','Localidad 11 suba').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(9).should('be.visible').click()
        cy.get('input[placeholder="Buscar..."]').type('Alberto lleras')
        cy.contains('ul li','Alberto lleras').click({force:true})
        cy.get('.text-xs.font-normal.w-4.h-4').first().should('be.visible').click({force:true})
        cy.contains('.button','Cancelar').scrollIntoView();
        cy.contains('button','Cancelar').should('be.visible')
        cy.contains('button','Guardar').should('be.visible').click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de realizar la creación del delegado?')
    })
    it('CP23_Confirmar creación exitosa', () => {
        const numeroDocumento = Math.floor(10000 + Math.random() * 90000)
        const correoAleatorio = `andre${Date.now()}@hotmail.com`
        cy.get('.bg-linear-90.button.duration-300.flex.flex-row.font-paragraph').click()
        cy.get('input[placeholder="Número de documento"]').eq(1).should('be.visible').type(numeroDocumento.toString())
        cy.get('svg[data-icon="magnifying-glass"]').first().click({ force: true })
        cy.get('input[placeholder="Nombres de usuario"]').should('be.visible')
        cy.get('input[placeholder="Apellidos de usuario"]').should('be.visible')
        cy.get('input[placeholder="Texto"]').first().should('be.visible').type('3102137409')
        cy.get('input[placeholder="Texto"]').eq(1).should('be.visible').type(correoAleatorio)
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({ force: true })
        cy.get('input[placeholder="Buscar..."]').type('Delegado puesto funcional')
        cy.contains('ul li', 'Delegado puesto funcional').click({ force: true })
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(8).should('be.visible').click()
        cy.get('input[placeholder="Buscar..."]').type('Localidad 11 suba')
        cy.contains('ul li', 'Localidad 11 suba').click({ force: true })
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(9).should('be.visible').click()
        cy.get('input[placeholder="Buscar..."]').type('Alberto lleras')
        cy.contains('ul li', 'Alberto lleras').click({ force: true })
        cy.get('.text-xs.font-normal.w-4.h-4').first().should('be.visible').click({ force: true })
        cy.contains('.button', 'Cancelar').scrollIntoView()
        cy.contains('button', 'Cancelar').should('be.visible')
        cy.contains('button', 'Guardar').should('be.visible').click({ force: true })
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text', '¿Está seguro de realizar la creación del delegado?')
        cy.contains('button','Sí').should('be.visible').click({force:true})
        cy.wait(2000)
        cy.contains('button','Editar').click({force:true})
        cy.contains('button', 'Guardar').scrollIntoView()
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').last().click()
        cy.contains('li','Inactivo').click()
        cy.get('.button.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full.items-center.justify-center.min-w-8.px-3.py-2').eq(6).click({force:true})
        cy.contains('button','Sí').should('be.visible').click({force:true})
        cy.wait(3000)
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300.flex.flex-row.font-paragraph').last().click({force:true})
        cy.contains('button', 'Guardar').should('be.visible').click({ force: true })
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text', '¿Está seguro de realizar la creación del delegado?')
        cy.contains('button','Sí').should('be.visible').click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','Delegado creado exitosamente')
    })
})