describe('63126 Creación de notificación automática para actividades y subactividades (ID: 64442)', ()=>{
    beforeEach( ()=>{
        allure.epic('Sprint 4')
        allure.feature('Creación de notificación automática para actividades y subactividades')
        cy.visit(Cypress.env('urlBase'))
        cy.get('input[placeholder="Usuario"]').type(Cypress.env('user'))
        cy.get('input[placeholder="Contraseña"]').type(Cypress.env('pass'))
        cy.wait(3000)
        cy.contains('button', 'Ingresar').click();
        cy.url().should("eq",'https://celerisawsqa.tps.net.co/dashboard')
        cy.contains('span','Administrar notificaciones automaticas').click({force:true})
        cy.url().should("eq",'https://celerisawsqa.tps.net.co/dashboard/alerts/manage-notification')
    })
    it('CP01_Apertura del modal Crear Notificación', ()=>{
        cy.get('.font-medium.text-h2.text-lg.text-white').should('be.visible').and('contain.text','Administración de notificaciones automáticas')
    })
    it('CP02_Validar encabezado del módulo', ()=>{
        cy.get('.font-medium.text-h2.text-lg.text-white').should('be.visible').and('contain.text','Administración de notificaciones automáticas')
        cy.contains('button','Crear notificación')
    })
    it('CP03_Validar panel lateral con menú Dashboard', ()=>{
        cy.get('a[href="/dashboard/alerts/manage-notification"]').should('have.class', 'bg-[#07055C]');
    })
    it('CP04_Verificar tarjetas de métricas visibles', ()=>{
        cy.get('.bg-white.flex.items-center.justify-between.min-h-24.min-w-60').should('have.length',2)
    })
    it('CP05_Validar estructura del formulario Crear Notificación', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.contains('h2','Sección Datos de la notificación')
        cy.contains('h2','Sección Contenido del mensaje')
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('h2','Previsualización del mensaje')
    })
    it('CP06_Validar campos de datos de la notificación', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible')
        cy.get('.flex.flex-wrap.gap-2.py-2.pr-2').first().should('be.visible')
        cy.get('input[type=date]').eq(0).should('be.visible')
        cy.get('input[type=date]').eq(1).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible')
        cy.get('.flex.items-center.shadow.rounded-lg.transition-all.p-3').should('be.visible')
        cy.contains('button','Agregar').should('be.visible')
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.get('.border.border-gray-300.rounded-md.p-4').first().should('be.visible')
        cy.contains('button','Cancelar').should('be.visible')
        cy.contains('button','Guardar').should('be.visible')
    })
    it('CP07_Validar campo Nombre de la etapa obligatorio', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('button','Guardar').should('be.visible').click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','La etapa es obligatoria')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300').last().should('be.visible').click({force:true})
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text',' Este campo es obligatorio. ')
    })
    it('CP08_Validar carga de etapas en lista desplegable', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force:true})
    })
    it('CP09_Validar dependencia Actividad - Etapa', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li','Automatizar actividad').click({force:true})
    })
    it('CP10_Validar dependencia Subactividad - Actividad', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li','Automatizar actividad').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizacion sub actividad no tocar')
        cy.contains('ul li','Automatizacion sub actividad no tocar').click({force:true})
    })
    it('CP11_Validar que Fechas de visualización sean solo lectura', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('input[type=date]').eq(0).should('be.visible').and('have.prop','disabled',true)
        cy.get('input[type=date]').eq(1).should('be.visible').and('have.prop','disabled',true)
    })
    it('CP12_Validar que Tipo de delegado se muestre correctamente', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li','Automatizar actividad').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizacion sub actividad no tocar')
        cy.contains('ul li','Automatizacion sub actividad no tocar').click({force:true})
        cy.get('.px-3.py-1.rounded-full.bg-blue-50.text-blue-700').should('be.visible').and('contain.text',' Delegados Puesto Logistico Funcional ')
    })
    it('CP13_Validar campo Estado por defecto', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-gray-100.bg-white.block.border.border-gray-300').should('be.visible').and('have.prop','innerText','Activo')
    })
    it('CP14_Validar presencia de campo Cuerpo de notificación', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('input[placeholder="Mensaje"]').first().type('Hola mundo')
    })
    it('CP15_Validar límite de 200 caracteres en cuerpo del mensaje', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('input[placeholder="Mensaje"]').first().type('Hola mundo Hola mundo Hola mundo Hola mundoHola mundoHola mundoHola mundoHola mundoHola mundoHola mundoHola mundoHola mundoHola mundoHola mundoHola mundoHola mundoHola mundoHola mundo')
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text',' Ha excedido el límite de caracteres permitido ')

    })
    it('CP16_Validar obligatoriedad del cuerpo del mensaje', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text',' Este campo es obligatorio. ')
    })
    it('CP17_Validar uso de parámetros en cuerpo del mensaje', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li','Automatizar actividad').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizacion sub actividad no tocar')
        cy.contains('ul li','Automatizacion sub actividad no tocar').click({force:true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('input[placeholder="Mensaje"]').first().type('E{nombre_etapa} A{Nombre_actividad} S{nombre_subactividad} I:{Hora_inicio_actividad}(Min-{minutos_inicio})Fin:{Hora_fin_actividad}(-Min{minutos_cierre})',{parseSpecialCharSequences : false})
    })
    it('CP18_Validar campo Hora de notificación', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible').click({force : true})
        cy.get('ul.text-ellipsis li').should('have.length', 12)
    })
    it('CP19_Validar selección de hora obligatoria', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible').click({force : true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text',' Este campo es obligatorio. ')
    })
    it('CP20_Validar que las listas desplegables permiten búsqueda', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li','Automatizar actividad').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizacion sub actividad no tocar')
        cy.contains('ul li','Automatizacion sub actividad no tocar').click({force:true})
    })
    it('CP21_Validar check “Requiere envío de mensaje de texto”', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.flex.items-center.shadow.rounded-lg.transition-all.p-3').first().should('be.visible').click({force:true})
    })
    it('CP22_Validar botón Agregar hora de notificación', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.contains('button','Agregar').should('be.visible').click({force:true})
    })
    it('CP23_Validar múltiples horas de notificación', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible').click({force : true})
        cy.get('ul.text-ellipsis li').contains('30 minutos antes del inicio').click()
        cy.contains('button','Agregar').should('be.visible').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(7).should('be.visible').click({force : true})
        cy.get('ul.text-ellipsis li').contains('25 minutos antes del inicio').click()
    })
    it('CP24_Validar previsualización de mensaje', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li','Automatizar actividad').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizacion sub actividad no tocar')
        cy.contains('ul li','Automatizacion sub actividad no tocar').click({force:true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('input[placeholder="Mensaje"]').first().type('E{nombre_etapa} A{Nombre_actividad} S{nombre_subactividad} I:{Hora_inicio_actividad}(Min-{minutos_inicio})Fin:{Hora_fin_actividad}(-Min{minutos_cierre})',{parseSpecialCharSequences : false})
        cy.get('.text-sm.text-gray-700').first().should('be.visible')
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('p','Los datos mostrados a continuación corresponden a un ejemplo con fines de previsualización')
    })
    it('CP25_Validar comportamiento de botón Cancelar', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('button','Cancelar').should('be.visible').click({force : true})
    })
    it('CP26_Validar botón de cierre (X)', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('button','Cerrar').should('be.visible').click({force : true})
    })
    it('CP27_Validar botón Guardar visible y activo', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('button','Guardar').should('be.visible')
    })
    it('CP28_Validar confirmación antes de crear notificación', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li','Automatizar actividad').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizacion sub actividad no tocar')
        cy.contains('ul li','Automatizacion sub actividad no tocar').click({force:true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('input[placeholder="Mensaje"]').first().type('E{nombre_etapa} A{Nombre_actividad} S{nombre_subactividad} I:{Hora_inicio_actividad}(Min-{minutos_inicio})Fin:{Hora_fin_actividad}(-Min{minutos_cierre})',{parseSpecialCharSequences : false})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible').click({force : true})
        cy.get('ul.text-ellipsis li').contains('30 minutos antes del inicio').click()
        cy.get('.flex.items-center.shadow.rounded-lg.transition-all.p-3').first().should('be.visible').click({force:true})
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('button','Guardar').should('be.visible').click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de realizar la creación de la notificación automática? Tenga en cuenta que se van a crear 1 cantidad de notificaciones automáticas')
    })
    it('CP29_Validar cálculo del número X de notificaciones', ()=>{
        cy.contains('button','Crear notificación').click({force : true})
        cy.contains('button','Crear notificación').click({force : true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li','Automatizar etapa').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li','Automatizar actividad').click({force:true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force:true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizacion sub actividad no tocar')
        cy.contains('ul li','Automatizacion sub actividad no tocar').click({force:true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('input[placeholder="Mensaje"]').first().type('E{nombre_etapa} A{Nombre_actividad} S{nombre_subactividad} I:{Hora_inicio_actividad}(Min-{minutos_inicio})Fin:{Hora_fin_actividad}(-Min{minutos_cierre})',{parseSpecialCharSequences : false})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible').click({force : true})
        cy.get('ul.text-ellipsis li').contains('30 minutos antes del inicio').click()
        cy.get('.flex.items-center.shadow.rounded-lg.transition-all.p-3').first().should('be.visible').click({force:true})
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('button','Guardar').should('be.visible').click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text', '1')
    })
    it('CP30_Validar creación exitosa', ()=> {
        cy.contains('button', 'Crear notificación').click({force: true})
        cy.contains('button', 'Crear notificación').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li', 'Automatizar etapa').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li', 'Automatizar actividad').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizacion sub actividad no tocar')
        cy.contains('ul li', 'Automatizacion sub actividad no tocar').click({force: true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('input[placeholder="Mensaje"]').first().type('E{nombre_etapa} A{Nombre_actividad} S{nombre_subactividad} I:{Hora_inicio_actividad}(Min-{minutos_inicio})Fin:{Hora_fin_actividad}(-Min{minutos_cierre})', {parseSpecialCharSequences: false})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible').click({force: true})
        cy.get('ul.text-ellipsis li').contains('30 minutos antes del inicio').click()
        cy.get('.flex.items-center.shadow.rounded-lg.transition-all.p-3').first().should('be.visible').click({force: true})
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('button', 'Guardar').should('be.visible').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text', '¿Está seguro de realizar la creación de la notificación automática? Tenga en cuenta que se van a crear 1 cantidad de notificaciones automáticas')
        cy.contains('button','Sí').should('be.visible').click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text', 'Notificación automática creada exitosamente.')
    })
    it('CP31_Validar cierre de modal tras creación', ()=> {
        cy.contains('button', 'Crear notificación').click({force: true})
        cy.contains('button', 'Crear notificación').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li', 'Automatizar etapa').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li', 'Automatizar actividad').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizacion sub actividad no tocar')
        cy.contains('ul li', 'Automatizacion sub actividad no tocar').click({force: true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('input[placeholder="Mensaje"]').first().type('E{nombre_etapa} A{Nombre_actividad} S{nombre_subactividad} I:{Hora_inicio_actividad}(Min-{minutos_inicio})Fin:{Hora_fin_actividad}(-Min{minutos_cierre})', {parseSpecialCharSequences: false})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible').click({force: true})
        cy.get('ul.text-ellipsis li').contains('30 minutos antes del inicio').click()
        cy.get('.flex.items-center.shadow.rounded-lg.transition-all.p-3').first().should('be.visible').click({force: true})
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('button', 'Guardar').should('be.visible').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text', '¿Está seguro de realizar la creación de la notificación automática? Tenga en cuenta que se van a crear 1 cantidad de notificaciones automáticas')
        cy.contains('button','Sí').should('be.visible').click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text', 'Notificación automática creada exitosamente.')
        cy.get('.bg-blue-btn').last().click()
    })
    it.only('CP32_Validar cancelación en confirmación', ()=> {
        cy.contains('button', 'Crear notificación').click({force: true})
        cy.contains('button', 'Crear notificación').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(3).should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar etapa')
        cy.contains('ul li', 'Automatizar etapa').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(4).should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizar actividad')
        cy.contains('ul li', 'Automatizar actividad').click({force: true})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(5).should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().should('be.visible').click({force: true})
        cy.get('input[placeholder="Buscar..."]').first().type('Automatizacion sub actividad no tocar')
        cy.contains('ul li', 'Automatizacion sub actividad no tocar').click({force: true})
        cy.get('input[placeholder="Mensaje"]').first().click()
        cy.get('input[placeholder="Mensaje"]').first().type('E{nombre_etapa} A{Nombre_actividad} S{nombre_subactividad} I:{Hora_inicio_actividad}(Min-{minutos_inicio})Fin:{Hora_fin_actividad}(-Min{minutos_cierre})', {parseSpecialCharSequences: false})
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(6).should('be.visible').click({force: true})
        cy.get('ul.text-ellipsis li').contains('30 minutos antes del inicio').click()
        cy.get('.flex.items-center.shadow.rounded-lg.transition-all.p-3').first().should('be.visible').click({force: true})
        cy.get('.border.border-gray-300.rounded-md.p-4').first().scrollIntoView();
        cy.contains('button', 'Guardar').should('be.visible').click({force: true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text', '¿Está seguro de realizar la creación de la notificación automática? Tenga en cuenta que se van a crear 1 cantidad de notificaciones automáticas')
        cy.contains('button','No').should('be.visible').click({force:true})
    })
})