describe('58140 Modificación de envío de alertas o notificación', ()=> {
    beforeEach( ()=>{
        allure.epic('Sprint 4')
        allure.feature('Modificación de envío de alertas o notificación')
        cy.visit(Cypress.env('urlBase'))
        cy.get('input[placeholder="Usuario"]').type(Cypress.env('user'))
        cy.get('input[placeholder="Contraseña"]').type(Cypress.env('pass'))
        cy.wait(3000)
        cy.contains('button', 'Ingresar').click();
        cy.url().should("eq",'https://celerisawsqa.tps.net.co/dashboard')
        cy.contains('span','Administrar Alertas o Notificaciones').click({force:true})
        cy.url().should("eq",'https://celerisawsqa.tps.net.co/dashboard/alerts/manage-alerts')
        cy.get('input[type="date"]').first().click()
        cy.get('input[type="date"]').first().type('2026-04-01', { delay: 300 })
        cy.wait(1000)
        cy.get('input[type="date"]').eq(1).click()
        cy.get('input[type="date"]').eq(1).type('2026-04-30')
        cy.contains('button','Consultar').click({force:true})
    })
    it('CP01_Validar el acceso a la funcionalidad', ()=>{
        cy.get('celeris-pencil-draw-outline-icon').last().should('be.visible').click({force:true})
        cy.contains('h3','Editar Alerta').should('be.visible')
    })
    it('CP02_Validar la estructura de la pantalla modificar', ()=>{
        cy.get('celeris-pencil-draw-outline-icon').last().should('be.visible').click({force:true})
        cy.contains('h3','Editar Alerta').should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(7).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(8).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(9).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(10).should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(11).should('be.visible')
        cy.get('.bg-white.block.min-w-full.overflow-x-hidden.px-4').last().should('be.visible')
        cy.get('input[placeholder="Escribe su mensaje..."]').last().should('be.visible')
        cy.get('input[type="date"]').eq(3).should('be.visible')
        cy.get('input[type="time"]').should('be.visible')
        cy.get('.flex.items-center.shadow.rounded-lg').should('be.visible');
        cy.get('.bg-white.text-black').should('be.visible');
        cy.get('.button.bg-blue-btn').last().scrollIntoView();
        cy.get('button.border-blue-900').should('be.visible');
        cy.get('button.bg-blue-btn').should('be.visible');
    })
    it('CP03_Validar los campos del formulario de modificación', ()=>{
        cy.get('celeris-pencil-draw-outline-icon').last().should('be.visible').click({force:true})
        cy.contains('h3','Editar Alerta').should('be.visible')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(7).should('be.visible').and('have.prop','innerText','Boyaca')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(8).should('be.visible').and('have.prop','innerText','Socha')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(9).should('be.visible').and('have.prop','innerText','Zona 00')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(10).should('be.visible').and('have.prop','innerText','Puesto cabecera municipal')
        cy.get('.bg-white.block.border.border-gray-300.cursor-pointer.duration-300').eq(11).should('be.visible').and('have.prop','innerText','1')
        cy.get('.bg-white.block.min-w-full.overflow-x-hidden.px-4.py-2').last().should('be.visible').and('have.prop','innerText','Jose')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible')
        cy.get('input[type="date"]').last().should('be.visible').and('have.prop','value','2026-04-30')
        cy.get('input[type="time"]').last().should('be.visible').and('have.prop','value','12:00')
        cy.get('.flex.items-center.shadow.rounded-lg.transition-all.p-3').eq(2).should('be.visible')
        cy.get('.flex.items-center.shadow.rounded-lg.transition-all.p-3').eq(3).should('be.visible')
        cy.get('.border.border-gray-300.rounded-md.p-4').last().should('be.visible')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300').last().scrollIntoView();
        cy.contains('button','Cancelar')
        cy.get('.button.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full.items-center.justify-center.min-w-8').last().should('be.visible')
        cy.fixture('crearEtapaPr').then((fixture)=>{
            const name = `${fixture.name2}`
            cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().type(name)
            cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text',' Ha excedido el límite de caracteres permitido. ')
        })
    })
    it('CP04_Validar errores y validaciones en la pantalla', ()=>{
        cy.get('celeris-pencil-draw-outline-icon').last().should('be.visible').click({force:true})
        cy.contains('h3','Editar Alerta').should('be.visible')
        cy.fixture('crearEtapaPr').then((fixture)=>{
            const name = `${fixture.name2}`
            cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().type(name)
            cy.get('.text-red-500.text-xs.italic.mt-1.flex.items-center').should('be.visible').and('contain.text',' Ha excedido el límite de caracteres permitido. ')
        })
    })
    it('CP05_Validar duplicidad de alertas',()=>{
        cy.get('celeris-pencil-draw-outline-icon').last().should('be.visible').click({force:true})
        cy.contains('h3','Editar Alerta').should('be.visible')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible').click()
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible').clear()
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible').type('Prueba qa #187')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300').last().scrollIntoView();
        cy.get('.button.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full.items-center.justify-center.min-w-8').last().should('be.visible').click()
        cy.contains('button','Sí').click()
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','Ya existe un mensaje con el mismo contenido programado recientemente a los destinatarios seleccionados. ¿Está seguro de que desea enviarlo nuevamente?')
    })
    it('CP06_Validar botones del formulario',()=>{
        cy.get('celeris-pencil-draw-outline-icon').last().should('be.visible').click({force:true})
        cy.contains('h3','Editar Alerta').should('be.visible')
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible').click()
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible').clear()
        cy.get('.block.w-full.py-2.bg-transparent.outline-none').last().should('be.visible').type('Prueba qa #187')
        cy.get('.bg-blue-btn.button.cursor-pointer.duration-300').last().scrollIntoView();
        cy.get('.button.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full.items-center.justify-center.min-w-8').last().should('be.visible').click()
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de realizar la actualización de la alerta o notificación?')
        cy.contains('button','No').click()
        cy.get('.button.duration-300.flex.flex-row.font-paragraph.font-semibold.h-full.items-center.justify-center.min-w-8').last().should('be.visible').click()
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','¿Está seguro de realizar la actualización de la alerta o notificación?')
        cy.contains('button','Sí').click()
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','Ya existe un mensaje con el mismo contenido programado recientemente a los destinatarios seleccionados. ¿Está seguro de que desea enviarlo nuevamente?')
        cy.reload()
        cy.wait(2000)
        cy.get('input[type="date"]').first().click()
        cy.get('input[type="date"]').first().type('2026-04-01', { delay: 300 })
        cy.wait(1000)
        cy.get('input[type="date"]').eq(1).click()
        cy.get('input[type="date"]').eq(1).type('2026-04-30')
        cy.contains('button','Consultar').click({force:true})
        cy.get('celeris-pencil-draw-outline-icon').first().should('be.visible').click({force:true})
        cy.get('.text-sm.text-gray-500.mt-2.px-4.font-paragraph').should('be.visible').and('contain.text','Solo se pueden editar alertas que se encuentren en estado Pendiente.')
    })
})